import type { OfficialCompatibilityAlias } from './types';

export const officialCompatibilityAliases: OfficialCompatibilityAlias[] = [
  {
    prototypeType: 'core.condition',
    officialType: 'lados.workflow.condition',
    officialPack: 'lados.workflow-foundation',
    canonicalCapability: 'workflow.control.condition',
    status: 'planned',
    migrationMode: 'alias',
    notes: 'Direct workflow control replacement.',
  },
  {
    prototypeType: 'core.logger',
    officialType: 'lados.workflow.write_log',
    officialPack: 'lados.workflow-foundation',
    canonicalCapability: 'workflow.log.write',
    status: 'planned',
    migrationMode: 'alias',
  },
  {
    prototypeType: 'resource.create',
    officialType: 'lados.resource.create',
    officialPack: 'lados.resource-operations',
    canonicalCapability: 'resource.create',
    status: 'planned',
    migrationMode: 'alias',
  },
  {
    prototypeType: 'artifact.write',
    officialType: 'lados.artifact.write',
    officialPack: 'lados.resource-operations',
    canonicalCapability: 'artifact.write',
    status: 'planned',
    migrationMode: 'alias',
  },
  {
    prototypeType: 'project.save_artifact',
    officialType: 'lados.artifact.write',
    officialPack: 'lados.resource-operations',
    canonicalCapability: 'artifact.write',
    status: 'planned',
    migrationMode: 'merge',
    notes: 'Legacy project artifact writer merges into official artifact write capability.',
  },
  {
    prototypeType: 'core.human_approval',
    officialType: 'lados.human.request_approval',
    officialPack: 'lados.human-work',
    canonicalCapability: 'human.approval.request',
    status: 'planned',
    migrationMode: 'merge',
  },
  {
    prototypeType: 'foundation.request_approval',
    officialType: 'lados.human.request_approval',
    officialPack: 'lados.human-work',
    canonicalCapability: 'human.approval.request',
    status: 'planned',
    migrationMode: 'merge',
  },
  {
    prototypeType: 'document.upload_file',
    officialType: 'lados.document.upload_file',
    officialPack: 'lados.document-intelligence',
    canonicalCapability: 'document.file.upload',
    status: 'planned',
    migrationMode: 'alias',
  },
  {
    prototypeType: 'document.read_excel',
    officialType: 'lados.document.read_excel',
    officialPack: 'lados.document-intelligence',
    canonicalCapability: 'document.table.read_excel',
    status: 'planned',
    migrationMode: 'alias',
  },
  {
    prototypeType: 'qs.read_boq',
    officialType: 'lados.qs.read_boq',
    officialPack: 'lados.qs-commercial',
    canonicalCapability: 'qs.boq.read',
    status: 'planned',
    migrationMode: 'alias',
  },
  {
    prototypeType: 'qs.classify_trade',
    officialType: 'lados.qs.classify_trade',
    officialPack: 'lados.qs-commercial',
    canonicalCapability: 'qs.trade.classify',
    status: 'planned',
    migrationMode: 'alias',
  },
  {
    prototypeType: 'construction.assess_progress_claim',
    officialType: 'lados.qs.assess_progress_claim',
    officialPack: 'lados.qs-commercial',
    canonicalCapability: 'qs.claim.assess',
    status: 'planned',
    migrationMode: 'manual_review',
    notes: 'Move from construction prototype to QS Commercial with explicit human review boundary.',
  },
  {
    prototypeType: 'notification.send_email',
    officialType: 'lados.communication.send_email',
    officialPack: 'lados.communication',
    canonicalCapability: 'communication.email.send',
    status: 'planned',
    migrationMode: 'alias',
  },
  {
    prototypeType: 'notification.send_sms',
    officialType: 'lados.communication.send_sms',
    officialPack: 'lados.communication',
    canonicalCapability: 'communication.sms.send',
    status: 'planned',
    migrationMode: 'alias',
  },
  {
    prototypeType: 'notification.send_in_app',
    officialType: 'lados.communication.send_in_app',
    officialPack: 'lados.communication',
    canonicalCapability: 'communication.in_app.send',
    status: 'planned',
    migrationMode: 'alias',
  },
  {
    prototypeType: 'foundation.send_notification',
    officialType: 'lados.communication.send_in_app',
    officialPack: 'lados.communication',
    canonicalCapability: 'communication.in_app.send',
    status: 'planned',
    migrationMode: 'merge',
    notes: 'Foundation notification concept merges into official Communication channel nodes.',
  },
  {
    prototypeType: 'finance.submit_invoice',
    officialType: 'lados.finance.submit_invoice',
    officialPack: 'lados.commercial-finance',
    canonicalCapability: 'finance.invoice.submit',
    status: 'planned',
    migrationMode: 'alias',
  },
  {
    prototypeType: 'finance.verify_invoice',
    officialType: 'lados.finance.verify_invoice',
    officialPack: 'lados.commercial-finance',
    canonicalCapability: 'finance.invoice.verify',
    status: 'planned',
    migrationMode: 'alias',
  },
  {
    prototypeType: 'finance.approve_invoice',
    officialType: 'lados.finance.record_invoice_approval',
    officialPack: 'lados.commercial-finance',
    canonicalCapability: 'finance.invoice.approval_record',
    status: 'planned',
    migrationMode: 'manual_review',
    notes: 'Approval action becomes record-human-approval to preserve the human decision boundary.',
  },
  {
    prototypeType: 'finance.process_payment',
    officialType: 'lados.finance.record_payment',
    officialPack: 'lados.commercial-finance',
    canonicalCapability: 'finance.payment.record',
    status: 'planned',
    migrationMode: 'manual_review',
    notes: 'Process payment becomes record payment unless a controlled integration executes payment.',
  },
  {
    prototypeType: 'contractor.record_payment',
    officialType: 'lados.finance.record_payment',
    officialPack: 'lados.commercial-finance',
    canonicalCapability: 'finance.payment.record',
    status: 'planned',
    migrationMode: 'merge',
  },
  {
    prototypeType: 'finance.create_purchase_order',
    officialType: 'lados.finance.create_purchase_order',
    officialPack: 'lados.commercial-finance',
    canonicalCapability: 'finance.po.create',
    status: 'planned',
    migrationMode: 'alias',
  },
  {
    prototypeType: 'procurement.generate_rfq',
    officialType: 'lados.procurement.create_rfq',
    officialPack: 'lados.procurement',
    canonicalCapability: 'procurement.rfq.create',
    status: 'planned',
    migrationMode: 'alias',
  },
  {
    prototypeType: 'procurement.generate_po',
    officialType: 'lados.procurement.generate_po_request',
    officialPack: 'lados.procurement',
    canonicalCapability: 'procurement.po.generate',
    status: 'planned',
    migrationMode: 'manual_review',
    notes: 'Procurement generates a PO request; Commercial Finance owns final PO creation and approval records.',
  },
  {
    prototypeType: 'construction.create_project',
    officialType: 'lados.construction.create_project',
    officialPack: 'lados.construction-operations',
    canonicalCapability: 'construction.project.create',
    status: 'planned',
    migrationMode: 'alias',
  },
  {
    prototypeType: 'construction.create_site_inspection',
    officialType: 'lados.construction.create_site_inspection',
    officialPack: 'lados.construction-operations',
    canonicalCapability: 'construction.inspection.create',
    status: 'planned',
    migrationMode: 'alias',
  },
  {
    prototypeType: 'construction.submit_inspection_report',
    officialType: 'lados.construction.submit_inspection_report',
    officialPack: 'lados.construction-operations',
    canonicalCapability: 'construction.inspection.submit_report',
    status: 'planned',
    migrationMode: 'alias',
  },
  {
    prototypeType: 'construction.log_defect',
    officialType: 'lados.construction.log_defect',
    officialPack: 'lados.construction-operations',
    canonicalCapability: 'construction.defect.log',
    status: 'planned',
    migrationMode: 'alias',
  },
  {
    prototypeType: 'contractor.create_job',
    officialType: 'lados.asset_fleet.create_job',
    officialPack: 'lados.asset-fleet',
    canonicalCapability: 'asset_fleet.job.create',
    status: 'planned',
    migrationMode: 'alias',
  },
  {
    prototypeType: 'contractor.dispatch_trip',
    officialType: 'lados.asset_fleet.dispatch_trip',
    officialPack: 'lados.asset-fleet',
    canonicalCapability: 'asset_fleet.trip.dispatch',
    status: 'planned',
    migrationMode: 'alias',
  },
  {
    prototypeType: 'contractor.complete_trip',
    officialType: 'lados.asset_fleet.complete_trip',
    officialPack: 'lados.asset-fleet',
    canonicalCapability: 'asset_fleet.trip.complete',
    status: 'planned',
    migrationMode: 'alias',
  },
  {
    prototypeType: 'contractor.upload_fuel_receipt',
    officialType: 'lados.asset_fleet.upload_fuel_receipt',
    officialPack: 'lados.asset-fleet',
    canonicalCapability: 'asset_fleet.fuel_receipt.upload',
    status: 'planned',
    migrationMode: 'alias',
  },
  {
    prototypeType: 'contractor.extract_fuel_data',
    officialType: 'lados.asset_fleet.extract_fuel_receipt',
    officialPack: 'lados.asset-fleet',
    canonicalCapability: 'asset_fleet.fuel_receipt.extract',
    status: 'planned',
    migrationMode: 'manual_review',
    notes: 'Fuel extraction becomes advisory with confidence and human review boundary.',
  },
  {
    prototypeType: 'contractor.create_maintenance_record',
    officialType: 'lados.asset_fleet.create_maintenance_record',
    officialPack: 'lados.asset-fleet',
    canonicalCapability: 'asset_fleet.maintenance.create',
    status: 'planned',
    migrationMode: 'alias',
  },
  {
    prototypeType: 'contractor.clear_maintenance',
    officialType: 'lados.asset_fleet.clear_maintenance',
    officialPack: 'lados.asset-fleet',
    canonicalCapability: 'asset_fleet.maintenance.clear',
    status: 'planned',
    migrationMode: 'manual_review',
    notes: 'Maintenance clearance must preserve responsible human or authorized integration metadata.',
  },
  {
    prototypeType: 'contractor.prepare_payroll_run',
    officialType: 'lados.people_payroll.prepare_payroll_run',
    officialPack: 'lados.people-payroll',
    canonicalCapability: 'people_payroll.payroll.prepare',
    status: 'planned',
    migrationMode: 'alias',
  },
  {
    prototypeType: 'contractor.approve_payroll',
    officialType: 'lados.people_payroll.record_payroll_approval',
    officialPack: 'lados.people-payroll',
    canonicalCapability: 'people_payroll.payroll.record_approval',
    status: 'planned',
    migrationMode: 'manual_review',
    notes: 'Approval action becomes record-human-approval to preserve human decision boundary.',
  },
  {
    prototypeType: 'contractor.approve_expense',
    officialType: 'lados.people_payroll.record_expense_approval',
    officialPack: 'lados.people-payroll',
    canonicalCapability: 'people_payroll.expense.record_approval',
    status: 'planned',
    migrationMode: 'manual_review',
    notes: 'Expense approval remains an explicit human-boundary record.',
  },
];

export function resolveOfficialCompatibilityAlias(
  prototypeType: string,
): OfficialCompatibilityAlias | undefined {
  return officialCompatibilityAliases.find((alias) => alias.prototypeType === prototypeType);
}
